name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Verify VSCE_PAT
        run: npx vsce verify-pat -p ${{ secrets.VSCE_TOKEN }}
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19
          extra_plugins: |
            @semantic-release/commit-analyzer@9
            @semantic-release/release-notes-generator@10
            @semantic-release/changelog@6
            @semantic-release/npm@9
            @semantic-release/git@10
            @semantic-release/github@8
            semantic-release-vsce@5.0.14
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
